### ISSUE TITLE
Release new gem

### ISSUE THREAD

**Issue by gotokatsuya** [medjed/embulk-input-bigquery#18]
0.0.2 is old...

**Comment by sonots** [comment]
@potato2003 ping. I think we can release gem once.

**Comment by potato2003** [comment]
@gotokatsuya (cc: @sonots) we released new version of gem.
- https://rubygems.org/gems/embulk-input-bigquery/versions/0.0.3

**Comment by gotokatsuya** [comment]
@potato2003 @sonots super thanks!
