### ISSUE TITLE
(NoMethodError) undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by 1987yama3** [medjed/embulk-input-bigquery#21]
```
org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `each' for nil:NilClass
	at RUBY.transaction(/Users/ryotayamada/github.com/principle.backlog/beluga-embulk/vendor/bundle/jruby/2.3.0/gems/embulk-input-bigquery-0.0.3/lib/embulk/input/bigquery.rb:31)
	at RUBY.transaction(uri:classloader:/embulk/input_plugin.rb:54)

Error: (NoMethodError) undefined method `each' for nil:NilClass
```

**Comment by 1987yama3** [comment]
I think following code is missing?

```
        rows.all do |row|
          columns = []
          @task[:columns].each do |c| 
            val = row[c['name'].to_sym]
            val = eval(c['eval'], binding) if c['eval']

            columns << as_serializable(val)
          end 

          @page_builder.add(columns)
        end 
```

The ```row``` variable is not symbolic hash. It is a string key hash in my environment.

So, I want to convert to ```row[c['name'].to_sym] || row[c['name'].to_s]```.

**Comment by sonots** [comment]
L31 is here https://github.com/medjed/embulk-input-bigquery/blob/master/lib/embulk/input/bigquery.rb#L31.

Please define at least one "erb_params" to avoid the problem for now.
@potato2003 I think empty "erb_params" should be acceptable. Can you fix?

**Comment by potato2003** [comment]
@1987yama3: I think your using 'google-cloud-bigquery' v0.23.

> The row variable is not symbolic hash. It is a string key hash in my environment.
> So, I want to convert to `row[c['name'].to_sym] || row[c['name'].to_s].`

```diff
- val = row[c['name']]
+ val = row[c['name'].to_sym]
```

this code has been fixed via #7 for support v0.24.
but, I think this is a change incompatible with v 02.3.

**Comment by potato2003** [comment]
> @potato2003 I think empty "erb_params" should be acceptable. Can you fix?

yes, i will fix it.

**Comment by sonots** [comment]
@potato2003 For the symbol problem, gemspec should be modified to "~> 0.24"

**Comment by potato2003** [comment]
We released new version of gem, which use embulk-input-bigquery v0.24+.
- https://rubygems.org/gems/embulk-input-bigquery/versions/0.0.4

**Comment by potato2003** [comment]
> @potato2003 I think empty "erb_params" should be acceptable. Can you fix?

fixed via https://github.com/medjed/embulk-input-bigquery/commit/206226ac49b87f8a610391b9b2c9635d140fbb68

**Comment by potato2003** [comment]
@1987yama3: Please try it with a new version. and let us know, if you find any problems with it.

**Comment by sonots** [comment]
Problem should be fixed. please reopen if you still have problems.
